import type { Metadata } from "next";
import { geistSans, geistMono, robotoSlab, nunito } from "@/lib/fonts";
import "./globals.css";
import { ReduxProvider } from "@/src/redux/Provider";
import { AuthProvider } from "@/src/context/AuthContext";
import { Toaster } from "sonner";
import { SessionExpiredModal } from "@/src/components/SessionExpiredModal";
import { OneSignalSetup } from "@/components/OneSignalSetup";
import { CompanyContextGuard } from "@/components/CompanyContextGuard";

export const metadata: Metadata = {
  title: "The Kriyona Studio",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${robotoSlab.variable} ${nunito.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthProvider>
            <CompanyContextGuard>
              <OneSignalSetup />
              {children}
            </CompanyContextGuard>
          </AuthProvider>
        </ReduxProvider>
        <Toaster position="top-right" richColors />
        <SessionExpiredModal />
      </body>
    </html>
  );
}
